profile="default"
profiles=["default"]
nmea.client=""
nmea.gps_id="APRMC"
imu.gyrobias=[3.09, -0.69, 1.19]
imu.rate=20
imu.alignmentQ=[0.999312072547677, -0.036938295474766396, 0.0033081698694946322, 0.0]
imu.heading_offset=0.0000
gps.filtered.output=false
wind.offset=0.0000
wind.sensors_height=0.0000
truewind.offset=0.0000
truewind.sensors_height=0.0000
rudder.offset=80.0
rudder.scale=100.0
rudder.nonlinearity=0.0
rudder.range=30.0000
apb.xte.gain=300.0000
servo.faults=0
servo.max_current=4.5000
servo.current.factor=1.0000
servo.current.offset=0.0000
servo.voltage.factor=1.0000
servo.voltage.offset=0.0000
servo.max_controller_temp=60.0000
servo.max_motor_temp=60.0000
servo.max_slew_speed=27.9528
servo.max_slew_slow=33.8583
servo.gain=1.0000
servo.clutch_pwm=100.0000
servo.use_brake=false
servo.compensate_current=false
servo.compensate_voltage=false
servo.amp_hours=0.00
servo.position.p=0.1500
servo.position.i=0.0000
servo.position.d=0.0200
servo.use_eeprom=true
ap.mode="compass"
ap.gps_and_nav_modes=true
ap.tack.count=0
ap.tack.use_heel=false
ap.tack.use_wind_direction=true
gps.filtered.enabled=false
signalk.enabled=true
signalk.period=0.5000
signalk.uid="pypilot-90687870926"
imu.accel.calibration=[[0.0000, 0.0000, 0.0000, 1.0000], 1.0000]
imu.accel.calibration.locked=false
imu.accel.calibration.points=false
imu.compass.calibration=[[0.0000, 0.0000, 0.0000, 30.0000, 0.0000], [1.0000, 1.0000], 0.0000]
imu.compass.calibration.locked=false
imu.compass.calibration.points=false
[profile="default"]
servo.period=0.4000
servo.speed.min=100.0000
servo.speed.max=100.0000
ap.pilot.absolute.P=0.0500
ap.pilot.absolute.I=0.0000
ap.pilot.absolute.D=0.2000
ap.pilot.absolute.DD=0.0000
ap.pilot.basic.P=0.0030
ap.pilot.basic.I=0.0000
ap.pilot.basic.D=0.0900
ap.pilot.basic.DD=0.0750
ap.pilot.basic.PR=0.0050
ap.pilot.basic.FF=0.6000
ap.pilot="basic"
ap.tack.delay=0.0000
ap.tack.angle=100.0000
ap.tack.rate=15.0000
ap.tack.threshold=50.0000
